// =============================================================================
//  Regenerates src/abis.generated.ts from the BlazePhoenix-Dex Solidity sources.
//
//    npm i --no-save solc@0.8.36
//    node scripts/gen-abis.mjs ../Blaze-Phoenix-Dex
//
//  ABIs are never written by hand: a hand-rolled fragment drifts silently the
//  day a struct gains a field. This compiles the real sources (ABI output only,
//  no codegen — seconds, not minutes) and emits one `as const` array per
//  contract so viem infers every argument and return type.
//
//  One deliberate edit, stated where it happens: `previewPlanExact` is declared
//  `nonpayable` in Solidity (it try/catches reverting dry-run swaps) but is only
//  ever reached through eth_call. It is emitted as `view` so a PublicClient can
//  read it; it never persists state either way.
// =============================================================================
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const dex = path.resolve(process.argv[2] ?? '../Blaze-Phoenix-Dex');
const out = path.resolve(process.argv[3] ?? 'src/abis.generated.ts');
const solc = require('solc');

const srcDir = path.join(dex, 'src');
const sources = {};
for (const f of fs.readdirSync(srcDir)) {
  if (f.endsWith('.sol')) sources[`src/${f}`] = { content: fs.readFileSync(path.join(srcDir, f), 'utf8') };
}
const input = {
  language: 'Solidity',
  sources,
  settings: { evmVersion: 'cancun', outputSelection: { '*': { '*': ['abi'] } } },
};
const findImports = (p) => {
  for (const base of [dex, path.join(dex, 'lib')]) {
    const fp = path.join(base, p);
    if (fs.existsSync(fp)) return { contents: fs.readFileSync(fp, 'utf8') };
  }
  return { error: `not found: ${p}` };
};
const res = JSON.parse(solc.compile(JSON.stringify(input), { import: findImports }));
const errors = (res.errors ?? []).filter((e) => e.severity === 'error');
if (errors.length) {
  for (const e of errors) console.error(e.formattedMessage);
  process.exit(1);
}

const strip = (v) => JSON.parse(JSON.stringify(v, (k, x) => (k === 'internalType' ? undefined : x)));
const abiOf = (file, name) => {
  const a = res.contracts?.[`src/${file}`]?.[name]?.abi;
  if (!a) throw new Error(`missing ${name} in ${file}`);
  return strip(a);
};

const core = abiOf('BlazePhoenixCore.sol', 'BlazePhoenixCore');
const hub = abiOf('BlazePhoenixHub.sol', 'BlazePhoenixHub');
const solver = abiOf('BlazePhoenixSolver.sol', 'BlazePhoenixSolver');
const quoter = abiOf('BlazePhoenixQuoter.sol', 'BlazePhoenixQuoter');
const router = abiOf('BlazePhoenixRouter.sol', 'BlazePhoenixRouter');

for (const it of quoter) {
  if (it.type === 'function' && it.name === 'previewPlanExact') it.stateMutability = 'view';
}

// Every custom error a quote or a swap can surface, so viem can decode a revert
// no matter which contract in the call stack raised it.
const errorsOf = (abi) => abi.filter((x) => x.type === 'error');
const allErrors = [...errorsOf(quoter), ...errorsOf(solver), ...errorsOf(hub), ...errorsOf(router)];
const withErrors = (abi) => {
  const have = new Set(abi.filter((x) => x.type === 'error').map((x) => x.name));
  return [...abi, ...allErrors.filter((e) => !have.has(e.name) && have.add(e.name))];
};

// Constructors, fallbacks and receive are deployment/runtime plumbing — an
// integrator never calls them, and viem's inference is cleaner without them.
const callable = (abi) => abi.filter((x) => x.type !== 'constructor' && x.type !== 'fallback' && x.type !== 'receive');

const emit = (name, abi) => `export const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n`;
const dexRev = (() => {
  try {
    const head = fs.readFileSync(path.join(dex, '.git', 'HEAD'), 'utf8').trim();
    if (!head.startsWith('ref:')) return head;
    const ref = head.slice(5).trim();
    const p = path.join(dex, '.git', ref);
    if (fs.existsSync(p)) return fs.readFileSync(p, 'utf8').trim();
    const packed = fs.readFileSync(path.join(dex, '.git', 'packed-refs'), 'utf8');
    return packed.split('\n').find((l) => l.endsWith(` ${ref}`))?.split(' ')[0] ?? 'unknown';
  } catch { return 'unknown'; }
})();

const body = [
  '// =============================================================================',
  '//  GENERATED by scripts/gen-abis.mjs from BlazePhoenix-Dex — do not edit.',
  `//  Source revision: ${dexRev}`,
  `//  Compiler: solc ${solc.version()}`,
  '//  previewPlanExact is emitted as `view` (eth_call only) — see the generator.',
  '// =============================================================================',
  '',
  emit('CORE_ABI', callable(core)),
  emit('HUB_ABI', withErrors(callable(hub))),
  emit('SOLVER_ABI', withErrors(callable(solver))),
  emit('QUOTER_ABI', withErrors(callable(quoter))),
  emit('ROUTER_ABI', withErrors(callable(router))),
  emit('BLAZE_ERRORS_ABI', allErrors),
  `export const ABI_SOURCE_REVISION = ${JSON.stringify(dexRev)} as const;\n`,
].join('\n');
fs.writeFileSync(out, body);
console.log(`wrote ${out} (dex ${dexRev.slice(0, 10)}, solc ${solc.version()})`);
