// =============================================================================
//  GENERATED by scripts/gen-abis.mjs from BlazePhoenix-Dex — do not edit.
//  Source revision: 07c85636f4116f98ddcfffb66e4477d7da7e9928
//  Compiler: solc 0.8.36+commit.8a079791.Emscripten.clang
//  previewPlanExact is emitted as `view` (eth_call only) — see the generator.
// =============================================================================

export const CORE_ABI = [
  {
    "inputs": [
      {
        "name": "factory",
        "type": "address"
      },
      {
        "name": "tA",
        "type": "address"
      },
      {
        "name": "tB",
        "type": "address"
      },
      {
        "name": "fee",
        "type": "uint24"
      },
      {
        "name": "stable",
        "type": "bool"
      },
      {
        "name": "tickSpacing",
        "type": "int24"
      },
      {
        "name": "mode",
        "type": "uint8"
      },
      {
        "name": "initCodeHash",
        "type": "bytes32"
      }
    ],
    "name": "deriveAddress",
    "outputs": [
      {
        "name": "pool",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "amountIn",
        "type": "uint256"
      },
      {
        "name": "sqrtP",
        "type": "uint160"
      },
      {
        "name": "liq",
        "type": "uint128"
      },
      {
        "name": "feePpm",
        "type": "uint24"
      },
      {
        "name": "zeroForOne",
        "type": "bool"
      }
    ],
    "name": "impactV3Bps",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "out",
        "type": "uint256"
      },
      {
        "name": "amountIn",
        "type": "uint256"
      },
      {
        "name": "sqrtP",
        "type": "uint160"
      },
      {
        "name": "zeroForOne",
        "type": "bool"
      }
    ],
    "name": "impactV3FromOut",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "ain",
        "type": "uint256"
      },
      {
        "name": "rIn",
        "type": "uint256"
      },
      {
        "name": "rOut",
        "type": "uint256"
      },
      {
        "name": "fee",
        "type": "uint256"
      },
      {
        "name": "stable",
        "type": "bool"
      }
    ],
    "name": "outSolidly",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "pool",
        "type": "address"
      },
      {
        "name": "kind",
        "type": "uint8"
      }
    ],
    "name": "provenShape",
    "outputs": [
      {
        "name": "ok",
        "type": "bool"
      },
      {
        "name": "k",
        "type": "uint8"
      },
      {
        "name": "fee",
        "type": "uint24"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "pool",
        "type": "address"
      },
      {
        "name": "stable",
        "type": "bool"
      },
      {
        "name": "cfgFee",
        "type": "uint256"
      }
    ],
    "name": "readDynamicFee",
    "outputs": [
      {
        "name": "fee",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "pool",
        "type": "address"
      },
      {
        "name": "kind",
        "type": "uint8"
      },
      {
        "name": "t0",
        "type": "address"
      },
      {
        "name": "t1",
        "type": "address"
      },
      {
        "name": "v4mgr",
        "type": "address"
      },
      {
        "name": "pid",
        "type": "bytes32"
      }
    ],
    "name": "registryDepth18",
    "outputs": [
      {
        "name": "depth",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "pool",
        "type": "address"
      },
      {
        "name": "amountIn",
        "type": "uint256"
      },
      {
        "name": "tokenIn",
        "type": "address"
      },
      {
        "name": "zeroForOne",
        "type": "bool"
      },
      {
        "name": "stable",
        "type": "bool"
      },
      {
        "name": "cfgFee",
        "type": "uint256"
      }
    ],
    "name": "solidlyAskOut",
    "outputs": [
      {
        "name": "out",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "pool",
        "type": "address"
      },
      {
        "name": "ain",
        "type": "uint256"
      },
      {
        "name": "rIn",
        "type": "uint256"
      },
      {
        "name": "rOut",
        "type": "uint256"
      },
      {
        "name": "stable",
        "type": "bool"
      },
      {
        "name": "cfgFee",
        "type": "uint256"
      },
      {
        "name": "tokenIn",
        "type": "address"
      }
    ],
    "name": "solidlyCurveOut",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "pool",
        "type": "address"
      },
      {
        "name": "amountIn",
        "type": "uint256"
      },
      {
        "name": "tokenIn",
        "type": "address"
      }
    ],
    "name": "solidlyGetAmountOut",
    "outputs": [
      {
        "name": "out",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "name": "kind",
            "type": "uint8"
          },
          {
            "name": "pool",
            "type": "address"
          },
          {
            "name": "zeroForOne",
            "type": "bool"
          },
          {
            "name": "fee",
            "type": "uint24"
          },
          {
            "name": "tickSpacing",
            "type": "int24"
          },
          {
            "name": "stable",
            "type": "bool"
          },
          {
            "name": "tokenIn",
            "type": "address"
          },
          {
            "name": "tokenOther",
            "type": "address"
          },
          {
            "name": "hooks",
            "type": "address"
          },
          {
            "name": "v4Manager",
            "type": "address"
          },
          {
            "name": "decIn1",
            "type": "uint8"
          },
          {
            "name": "decOther1",
            "type": "uint8"
          }
        ],
        "name": "c",
        "type": "tuple"
      },
      {
        "name": "amountIn",
        "type": "uint256"
      }
    ],
    "name": "universalQuote",
    "outputs": [
      {
        "name": "out",
        "type": "uint256"
      },
      {
        "name": "depthWad",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "manager",
        "type": "address"
      },
      {
        "name": "poolId",
        "type": "bytes32"
      },
      {
        "name": "amountIn",
        "type": "uint256"
      },
      {
        "name": "keyFee",
        "type": "uint24"
      },
      {
        "name": "tickSpacing",
        "type": "int24"
      },
      {
        "name": "zeroForOne",
        "type": "bool"
      }
    ],
    "name": "v4LegOut",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "manager",
        "type": "address"
      },
      {
        "name": "poolId",
        "type": "bytes32"
      }
    ],
    "name": "v4SqrtAndLiq",
    "outputs": [
      {
        "name": "sqrtP",
        "type": "uint160"
      },
      {
        "name": "liq",
        "type": "uint128"
      },
      {
        "name": "lpFee",
        "type": "uint24"
      },
      {
        "name": "protoFee",
        "type": "uint24"
      },
      {
        "name": "tick",
        "type": "int24"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "manager",
        "type": "address"
      },
      {
        "name": "poolId",
        "type": "bytes32"
      },
      {
        "name": "amountIn",
        "type": "uint256"
      },
      {
        "name": "fee",
        "type": "uint24"
      },
      {
        "name": "tickSpacing",
        "type": "int24"
      },
      {
        "name": "zeroForOne",
        "type": "bool"
      }
    ],
    "name": "v4WalkOut",
    "outputs": [
      {
        "name": "out",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

export const HUB_ABI = [
  {
    "inputs": [
      {
        "name": "code",
        "type": "uint16"
      }
    ],
    "name": "HubE",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "token",
        "type": "address"
      },
      {
        "indexed": false,
        "name": "added",
        "type": "bool"
      }
    ],
    "name": "Bridge_",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [],
    "name": "ControlRenounced",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "key",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "name": "pool",
        "type": "address"
      }
    ],
    "name": "Evicted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "factory",
        "type": "address"
      },
      {
        "indexed": false,
        "name": "kind",
        "type": "uint8"
      },
      {
        "indexed": false,
        "name": "mode",
        "type": "uint8"
      }
    ],
    "name": "Factory_",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "name": "paused",
        "type": "bool"
      }
    ],
    "name": "PausedSet",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "key",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "name": "pool",
        "type": "address"
      },
      {
        "indexed": false,
        "name": "kind",
        "type": "uint8"
      }
    ],
    "name": "Registered",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "name": "role",
        "type": "uint8"
      },
      {
        "indexed": false,
        "name": "who",
        "type": "address"
      }
    ],
    "name": "RoleSet",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "idx",
        "type": "uint256"
      },
      {
        "indexed": false,
        "name": "c0",
        "type": "address"
      },
      {
        "indexed": false,
        "name": "c1",
        "type": "address"
      },
      {
        "indexed": false,
        "name": "fee",
        "type": "uint24"
      }
    ],
    "name": "V4Add",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "key",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "name": "amtIn",
        "type": "uint256"
      },
      {
        "indexed": false,
        "name": "amtOut",
        "type": "uint256"
      }
    ],
    "name": "Volume",
    "type": "event"
  },
  {
    "inputs": [
      {
        "name": "t",
        "type": "address"
      }
    ],
    "name": "addBridge",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "factory",
        "type": "address"
      },
      {
        "name": "kind",
        "type": "uint8"
      },
      {
        "name": "mode",
        "type": "uint8"
      },
      {
        "name": "initHash",
        "type": "bytes32"
      },
      {
        "name": "fees",
        "type": "uint24[]"
      },
      {
        "name": "spacings",
        "type": "int24[]"
      }
    ],
    "name": "addFactory",
    "outputs": [
      {
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "c0",
        "type": "address"
      },
      {
        "name": "c1",
        "type": "address"
      },
      {
        "name": "fee",
        "type": "uint24"
      },
      {
        "name": "tickSpacing",
        "type": "int24"
      },
      {
        "name": "hooks",
        "type": "address"
      }
    ],
    "name": "addV4",
    "outputs": [
      {
        "name": "key",
        "type": "bytes32"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "h",
        "type": "address"
      },
      {
        "name": "ok",
        "type": "bool"
      }
    ],
    "name": "allowHook",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "i",
        "type": "uint8"
      }
    ],
    "name": "bridge",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "bridgeCount",
    "outputs": [
      {
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "c0",
        "type": "address"
      },
      {
        "name": "c1",
        "type": "address"
      },
      {
        "name": "fee",
        "type": "uint24"
      },
      {
        "name": "tickSpacing",
        "type": "int24"
      }
    ],
    "name": "claimV4",
    "outputs": [
      {
        "name": "key",
        "type": "bytes32"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "tA",
        "type": "address"
      },
      {
        "name": "tB",
        "type": "address"
      }
    ],
    "name": "discoverFor",
    "outputs": [
      {
        "components": [
          {
            "name": "active",
            "type": "bool"
          },
          {
            "name": "stable",
            "type": "bool"
          },
          {
            "name": "kind",
            "type": "uint8"
          },
          {
            "name": "fee",
            "type": "uint24"
          },
          {
            "name": "tickSpacing",
            "type": "int24"
          },
          {
            "name": "token0",
            "type": "address"
          },
          {
            "name": "token1",
            "type": "address"
          },
          {
            "name": "pool",
            "type": "address"
          },
          {
            "name": "hooks",
            "type": "address"
          }
        ],
        "name": "hits",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "factoryCount",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "tA",
        "type": "address"
      },
      {
        "name": "tB",
        "type": "address"
      }
    ],
    "name": "getActivePools",
    "outputs": [
      {
        "components": [
          {
            "name": "active",
            "type": "bool"
          },
          {
            "name": "stable",
            "type": "bool"
          },
          {
            "name": "kind",
            "type": "uint8"
          },
          {
            "name": "fee",
            "type": "uint24"
          },
          {
            "name": "tickSpacing",
            "type": "int24"
          },
          {
            "name": "token0",
            "type": "address"
          },
          {
            "name": "token1",
            "type": "address"
          },
          {
            "name": "pool",
            "type": "address"
          },
          {
            "name": "hooks",
            "type": "address"
          }
        ],
        "name": "out",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "key",
        "type": "bytes32"
      }
    ],
    "name": "getPool",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "pool",
        "type": "address"
      },
      {
        "name": "tA",
        "type": "address"
      },
      {
        "name": "tB",
        "type": "address"
      }
    ],
    "name": "getPsi",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "key",
        "type": "bytes32"
      }
    ],
    "name": "getSlot",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "h",
        "type": "address"
      }
    ],
    "name": "hookPaused",
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "admin_",
        "type": "address"
      },
      {
        "name": "v4Manager_",
        "type": "address"
      }
    ],
    "name": "initialize",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "t",
        "type": "address"
      }
    ],
    "name": "isBridgeToken",
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "h",
        "type": "address"
      }
    ],
    "name": "isHookLive",
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "t",
        "type": "address"
      }
    ],
    "name": "isRoutableBridge",
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "pool",
        "type": "address"
      },
      {
        "name": "tA",
        "type": "address"
      },
      {
        "name": "tB",
        "type": "address"
      }
    ],
    "name": "keyOf",
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "pools",
        "type": "address[]"
      },
      {
        "name": "tAs",
        "type": "address[]"
      },
      {
        "name": "tBs",
        "type": "address[]"
      }
    ],
    "name": "psisOf",
    "outputs": [
      {
        "name": "ps",
        "type": "uint256[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "pool",
        "type": "address"
      },
      {
        "name": "kind",
        "type": "uint8"
      },
      {
        "name": "fee",
        "type": "uint24"
      },
      {
        "name": "hooks",
        "type": "address"
      },
      {
        "name": "tA",
        "type": "address"
      },
      {
        "name": "tB",
        "type": "address"
      },
      {
        "name": "amtIn",
        "type": "uint256"
      },
      {
        "name": "amtOut",
        "type": "uint256"
      },
      {
        "name": "depthWad",
        "type": "uint256"
      }
    ],
    "name": "recordSwap",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "idx",
        "type": "uint8"
      }
    ],
    "name": "removeBridge",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "renounceControl",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "pool",
        "type": "address"
      },
      {
        "name": "kind",
        "type": "uint8"
      },
      {
        "name": "fee",
        "type": "uint24"
      },
      {
        "name": "hooks",
        "type": "address"
      },
      {
        "name": "tA",
        "type": "address"
      },
      {
        "name": "tB",
        "type": "address"
      }
    ],
    "name": "seedPool",
    "outputs": [
      {
        "name": "key",
        "type": "bytes32"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "who",
        "type": "address"
      },
      {
        "name": "ok",
        "type": "bool"
      }
    ],
    "name": "setOperator",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "b",
        "type": "bool"
      }
    ],
    "name": "setPaused",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "r",
        "type": "address"
      },
      {
        "name": "s",
        "type": "address"
      },
      {
        "name": "q",
        "type": "address"
      }
    ],
    "name": "setRoles",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "m",
        "type": "address"
      }
    ],
    "name": "setV4Manager",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "token",
        "type": "address"
      }
    ],
    "name": "v4CodeOf",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "v4EntryCount",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "v4PoolManager",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "code",
        "type": "uint16"
      }
    ],
    "name": "QuoterE",
    "type": "error"
  },
  {
    "inputs": [
      {
        "name": "code",
        "type": "uint16"
      }
    ],
    "name": "SolverE",
    "type": "error"
  },
  {
    "inputs": [
      {
        "name": "code",
        "type": "uint16"
      }
    ],
    "name": "RouterE",
    "type": "error"
  }
] as const;

export const SOLVER_ABI = [
  {
    "inputs": [
      {
        "name": "code",
        "type": "uint16"
      }
    ],
    "name": "SolverE",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "VERSION",
    "outputs": [
      {
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "tIn",
        "type": "address"
      },
      {
        "name": "tOut",
        "type": "address"
      },
      {
        "name": "amountIn",
        "type": "uint256"
      }
    ],
    "name": "findBestRoutePlan",
    "outputs": [
      {
        "components": [
          {
            "components": [
              {
                "components": [
                  {
                    "name": "tokenIn",
                    "type": "address"
                  },
                  {
                    "name": "tokenOut",
                    "type": "address"
                  },
                  {
                    "name": "amountIn",
                    "type": "uint256"
                  },
                  {
                    "name": "expectedOut",
                    "type": "uint256"
                  },
                  {
                    "components": [
                      {
                        "name": "pool",
                        "type": "address"
                      },
                      {
                        "name": "hooks",
                        "type": "address"
                      },
                      {
                        "name": "kind",
                        "type": "uint8"
                      },
                      {
                        "name": "fee",
                        "type": "uint24"
                      },
                      {
                        "name": "tickSpacing",
                        "type": "int24"
                      },
                      {
                        "name": "zeroForOne",
                        "type": "bool"
                      },
                      {
                        "name": "stable",
                        "type": "bool"
                      },
                      {
                        "name": "amountIn",
                        "type": "uint256"
                      },
                      {
                        "name": "expectedOut",
                        "type": "uint256"
                      },
                      {
                        "name": "auxId",
                        "type": "bytes32"
                      }
                    ],
                    "name": "legs",
                    "type": "tuple[]"
                  }
                ],
                "name": "hops",
                "type": "tuple[]"
              },
              {
                "name": "totalOut",
                "type": "uint256"
              },
              {
                "name": "singleOut",
                "type": "uint256"
              },
              {
                "name": "singleOutFloor",
                "type": "uint256"
              },
              {
                "name": "expectedImpactBps",
                "type": "uint256"
              },
              {
                "name": "confidenceWad",
                "type": "uint256"
              },
              {
                "name": "estGas",
                "type": "uint256"
              },
              {
                "name": "hasSurplus",
                "type": "bool"
              },
              {
                "name": "isV4Bundle",
                "type": "bool"
              }
            ],
            "name": "best",
            "type": "tuple"
          },
          {
            "components": [
              {
                "components": [
                  {
                    "name": "tokenIn",
                    "type": "address"
                  },
                  {
                    "name": "tokenOut",
                    "type": "address"
                  },
                  {
                    "name": "amountIn",
                    "type": "uint256"
                  },
                  {
                    "name": "expectedOut",
                    "type": "uint256"
                  },
                  {
                    "components": [
                      {
                        "name": "pool",
                        "type": "address"
                      },
                      {
                        "name": "hooks",
                        "type": "address"
                      },
                      {
                        "name": "kind",
                        "type": "uint8"
                      },
                      {
                        "name": "fee",
                        "type": "uint24"
                      },
                      {
                        "name": "tickSpacing",
                        "type": "int24"
                      },
                      {
                        "name": "zeroForOne",
                        "type": "bool"
                      },
                      {
                        "name": "stable",
                        "type": "bool"
                      },
                      {
                        "name": "amountIn",
                        "type": "uint256"
                      },
                      {
                        "name": "expectedOut",
                        "type": "uint256"
                      },
                      {
                        "name": "auxId",
                        "type": "bytes32"
                      }
                    ],
                    "name": "legs",
                    "type": "tuple[]"
                  }
                ],
                "name": "hops",
                "type": "tuple[]"
              },
              {
                "name": "totalOut",
                "type": "uint256"
              },
              {
                "name": "singleOut",
                "type": "uint256"
              },
              {
                "name": "singleOutFloor",
                "type": "uint256"
              },
              {
                "name": "expectedImpactBps",
                "type": "uint256"
              },
              {
                "name": "confidenceWad",
                "type": "uint256"
              },
              {
                "name": "estGas",
                "type": "uint256"
              },
              {
                "name": "hasSurplus",
                "type": "bool"
              },
              {
                "name": "isV4Bundle",
                "type": "bool"
              }
            ],
            "name": "fallbackRoute",
            "type": "tuple"
          },
          {
            "name": "hasFallback",
            "type": "bool"
          }
        ],
        "name": "plan",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "hub",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "code",
        "type": "uint16"
      }
    ],
    "name": "QuoterE",
    "type": "error"
  },
  {
    "inputs": [
      {
        "name": "code",
        "type": "uint16"
      }
    ],
    "name": "HubE",
    "type": "error"
  },
  {
    "inputs": [
      {
        "name": "code",
        "type": "uint16"
      }
    ],
    "name": "RouterE",
    "type": "error"
  }
] as const;

export const QUOTER_ABI = [
  {
    "inputs": [
      {
        "name": "code",
        "type": "uint16"
      }
    ],
    "name": "QuoterE",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "VERSION",
    "outputs": [
      {
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "name": "tIn",
            "type": "address"
          },
          {
            "name": "tOut",
            "type": "address"
          },
          {
            "name": "amountIn",
            "type": "uint256"
          },
          {
            "name": "userMinOut",
            "type": "uint256"
          }
        ],
        "name": "entries",
        "type": "tuple[]"
      }
    ],
    "name": "batchQuote",
    "outputs": [
      {
        "components": [
          {
            "components": [
              {
                "components": [
                  {
                    "name": "tokenIn",
                    "type": "address"
                  },
                  {
                    "name": "tokenOut",
                    "type": "address"
                  },
                  {
                    "name": "amountIn",
                    "type": "uint256"
                  },
                  {
                    "name": "expectedOut",
                    "type": "uint256"
                  },
                  {
                    "components": [
                      {
                        "name": "pool",
                        "type": "address"
                      },
                      {
                        "name": "hooks",
                        "type": "address"
                      },
                      {
                        "name": "kind",
                        "type": "uint8"
                      },
                      {
                        "name": "fee",
                        "type": "uint24"
                      },
                      {
                        "name": "tickSpacing",
                        "type": "int24"
                      },
                      {
                        "name": "zeroForOne",
                        "type": "bool"
                      },
                      {
                        "name": "stable",
                        "type": "bool"
                      },
                      {
                        "name": "amountIn",
                        "type": "uint256"
                      },
                      {
                        "name": "expectedOut",
                        "type": "uint256"
                      },
                      {
                        "name": "auxId",
                        "type": "bytes32"
                      }
                    ],
                    "name": "legs",
                    "type": "tuple[]"
                  }
                ],
                "name": "hops",
                "type": "tuple[]"
              },
              {
                "name": "totalOut",
                "type": "uint256"
              },
              {
                "name": "singleOut",
                "type": "uint256"
              },
              {
                "name": "singleOutFloor",
                "type": "uint256"
              },
              {
                "name": "expectedImpactBps",
                "type": "uint256"
              },
              {
                "name": "confidenceWad",
                "type": "uint256"
              },
              {
                "name": "estGas",
                "type": "uint256"
              },
              {
                "name": "hasSurplus",
                "type": "bool"
              },
              {
                "name": "isV4Bundle",
                "type": "bool"
              }
            ],
            "name": "route",
            "type": "tuple"
          },
          {
            "name": "grossOut",
            "type": "uint256"
          },
          {
            "name": "protocolFee",
            "type": "uint256"
          },
          {
            "name": "safetyBuffer",
            "type": "uint256"
          },
          {
            "name": "netOut",
            "type": "uint256"
          },
          {
            "name": "ironFloor",
            "type": "uint256"
          },
          {
            "name": "userMinOut",
            "type": "uint256"
          },
          {
            "name": "effectiveMinOut",
            "type": "uint256"
          },
          {
            "name": "estGas",
            "type": "uint256"
          },
          {
            "name": "hops",
            "type": "uint256"
          },
          {
            "name": "legs",
            "type": "uint256"
          },
          {
            "name": "topology",
            "type": "uint8"
          },
          {
            "name": "bridgeUsed",
            "type": "address"
          },
          {
            "name": "canExecute",
            "type": "bool"
          }
        ],
        "name": "previews",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "i",
        "type": "uint8"
      }
    ],
    "name": "bridgeAt",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "bridgesCount",
    "outputs": [
      {
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "hub",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "t",
        "type": "address"
      }
    ],
    "name": "isBridge",
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "tIn",
        "type": "address"
      },
      {
        "name": "tOut",
        "type": "address"
      },
      {
        "name": "amountIn",
        "type": "uint256"
      },
      {
        "name": "recipient",
        "type": "address"
      },
      {
        "name": "deadline",
        "type": "uint256"
      }
    ],
    "name": "previewAndEncode",
    "outputs": [
      {
        "components": [
          {
            "components": [
              {
                "components": [
                  {
                    "name": "tokenIn",
                    "type": "address"
                  },
                  {
                    "name": "tokenOut",
                    "type": "address"
                  },
                  {
                    "name": "amountIn",
                    "type": "uint256"
                  },
                  {
                    "name": "expectedOut",
                    "type": "uint256"
                  },
                  {
                    "components": [
                      {
                        "name": "pool",
                        "type": "address"
                      },
                      {
                        "name": "hooks",
                        "type": "address"
                      },
                      {
                        "name": "kind",
                        "type": "uint8"
                      },
                      {
                        "name": "fee",
                        "type": "uint24"
                      },
                      {
                        "name": "tickSpacing",
                        "type": "int24"
                      },
                      {
                        "name": "zeroForOne",
                        "type": "bool"
                      },
                      {
                        "name": "stable",
                        "type": "bool"
                      },
                      {
                        "name": "amountIn",
                        "type": "uint256"
                      },
                      {
                        "name": "expectedOut",
                        "type": "uint256"
                      },
                      {
                        "name": "auxId",
                        "type": "bytes32"
                      }
                    ],
                    "name": "legs",
                    "type": "tuple[]"
                  }
                ],
                "name": "hops",
                "type": "tuple[]"
              },
              {
                "name": "totalOut",
                "type": "uint256"
              },
              {
                "name": "singleOut",
                "type": "uint256"
              },
              {
                "name": "singleOutFloor",
                "type": "uint256"
              },
              {
                "name": "expectedImpactBps",
                "type": "uint256"
              },
              {
                "name": "confidenceWad",
                "type": "uint256"
              },
              {
                "name": "estGas",
                "type": "uint256"
              },
              {
                "name": "hasSurplus",
                "type": "bool"
              },
              {
                "name": "isV4Bundle",
                "type": "bool"
              }
            ],
            "name": "route",
            "type": "tuple"
          },
          {
            "name": "grossOut",
            "type": "uint256"
          },
          {
            "name": "protocolFee",
            "type": "uint256"
          },
          {
            "name": "safetyBuffer",
            "type": "uint256"
          },
          {
            "name": "netOut",
            "type": "uint256"
          },
          {
            "name": "ironFloor",
            "type": "uint256"
          },
          {
            "name": "userMinOut",
            "type": "uint256"
          },
          {
            "name": "effectiveMinOut",
            "type": "uint256"
          },
          {
            "name": "estGas",
            "type": "uint256"
          },
          {
            "name": "hops",
            "type": "uint256"
          },
          {
            "name": "legs",
            "type": "uint256"
          },
          {
            "name": "topology",
            "type": "uint8"
          },
          {
            "name": "bridgeUsed",
            "type": "address"
          },
          {
            "name": "canExecute",
            "type": "bool"
          }
        ],
        "name": "pv",
        "type": "tuple"
      },
      {
        "name": "call",
        "type": "bytes"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "tIn",
        "type": "address"
      },
      {
        "name": "tOut",
        "type": "address"
      },
      {
        "name": "amountIn",
        "type": "uint256"
      },
      {
        "name": "userMinOut",
        "type": "uint256"
      },
      {
        "name": "recipient",
        "type": "address"
      },
      {
        "name": "deadline",
        "type": "uint256"
      }
    ],
    "name": "previewAndEncodeWithMinOut",
    "outputs": [
      {
        "components": [
          {
            "components": [
              {
                "components": [
                  {
                    "name": "tokenIn",
                    "type": "address"
                  },
                  {
                    "name": "tokenOut",
                    "type": "address"
                  },
                  {
                    "name": "amountIn",
                    "type": "uint256"
                  },
                  {
                    "name": "expectedOut",
                    "type": "uint256"
                  },
                  {
                    "components": [
                      {
                        "name": "pool",
                        "type": "address"
                      },
                      {
                        "name": "hooks",
                        "type": "address"
                      },
                      {
                        "name": "kind",
                        "type": "uint8"
                      },
                      {
                        "name": "fee",
                        "type": "uint24"
                      },
                      {
                        "name": "tickSpacing",
                        "type": "int24"
                      },
                      {
                        "name": "zeroForOne",
                        "type": "bool"
                      },
                      {
                        "name": "stable",
                        "type": "bool"
                      },
                      {
                        "name": "amountIn",
                        "type": "uint256"
                      },
                      {
                        "name": "expectedOut",
                        "type": "uint256"
                      },
                      {
                        "name": "auxId",
                        "type": "bytes32"
                      }
                    ],
                    "name": "legs",
                    "type": "tuple[]"
                  }
                ],
                "name": "hops",
                "type": "tuple[]"
              },
              {
                "name": "totalOut",
                "type": "uint256"
              },
              {
                "name": "singleOut",
                "type": "uint256"
              },
              {
                "name": "singleOutFloor",
                "type": "uint256"
              },
              {
                "name": "expectedImpactBps",
                "type": "uint256"
              },
              {
                "name": "confidenceWad",
                "type": "uint256"
              },
              {
                "name": "estGas",
                "type": "uint256"
              },
              {
                "name": "hasSurplus",
                "type": "bool"
              },
              {
                "name": "isV4Bundle",
                "type": "bool"
              }
            ],
            "name": "route",
            "type": "tuple"
          },
          {
            "name": "grossOut",
            "type": "uint256"
          },
          {
            "name": "protocolFee",
            "type": "uint256"
          },
          {
            "name": "safetyBuffer",
            "type": "uint256"
          },
          {
            "name": "netOut",
            "type": "uint256"
          },
          {
            "name": "ironFloor",
            "type": "uint256"
          },
          {
            "name": "userMinOut",
            "type": "uint256"
          },
          {
            "name": "effectiveMinOut",
            "type": "uint256"
          },
          {
            "name": "estGas",
            "type": "uint256"
          },
          {
            "name": "hops",
            "type": "uint256"
          },
          {
            "name": "legs",
            "type": "uint256"
          },
          {
            "name": "topology",
            "type": "uint8"
          },
          {
            "name": "bridgeUsed",
            "type": "address"
          },
          {
            "name": "canExecute",
            "type": "bool"
          }
        ],
        "name": "pv",
        "type": "tuple"
      },
      {
        "name": "call",
        "type": "bytes"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "tIn",
        "type": "address"
      },
      {
        "name": "tOut",
        "type": "address"
      },
      {
        "name": "amountIn",
        "type": "uint256"
      }
    ],
    "name": "previewPlan",
    "outputs": [
      {
        "components": [
          {
            "components": [
              {
                "components": [
                  {
                    "name": "tokenIn",
                    "type": "address"
                  },
                  {
                    "name": "tokenOut",
                    "type": "address"
                  },
                  {
                    "name": "amountIn",
                    "type": "uint256"
                  },
                  {
                    "name": "expectedOut",
                    "type": "uint256"
                  },
                  {
                    "components": [
                      {
                        "name": "pool",
                        "type": "address"
                      },
                      {
                        "name": "hooks",
                        "type": "address"
                      },
                      {
                        "name": "kind",
                        "type": "uint8"
                      },
                      {
                        "name": "fee",
                        "type": "uint24"
                      },
                      {
                        "name": "tickSpacing",
                        "type": "int24"
                      },
                      {
                        "name": "zeroForOne",
                        "type": "bool"
                      },
                      {
                        "name": "stable",
                        "type": "bool"
                      },
                      {
                        "name": "amountIn",
                        "type": "uint256"
                      },
                      {
                        "name": "expectedOut",
                        "type": "uint256"
                      },
                      {
                        "name": "auxId",
                        "type": "bytes32"
                      }
                    ],
                    "name": "legs",
                    "type": "tuple[]"
                  }
                ],
                "name": "hops",
                "type": "tuple[]"
              },
              {
                "name": "totalOut",
                "type": "uint256"
              },
              {
                "name": "singleOut",
                "type": "uint256"
              },
              {
                "name": "singleOutFloor",
                "type": "uint256"
              },
              {
                "name": "expectedImpactBps",
                "type": "uint256"
              },
              {
                "name": "confidenceWad",
                "type": "uint256"
              },
              {
                "name": "estGas",
                "type": "uint256"
              },
              {
                "name": "hasSurplus",
                "type": "bool"
              },
              {
                "name": "isV4Bundle",
                "type": "bool"
              }
            ],
            "name": "route",
            "type": "tuple"
          },
          {
            "name": "grossOut",
            "type": "uint256"
          },
          {
            "name": "protocolFee",
            "type": "uint256"
          },
          {
            "name": "safetyBuffer",
            "type": "uint256"
          },
          {
            "name": "netOut",
            "type": "uint256"
          },
          {
            "name": "ironFloor",
            "type": "uint256"
          },
          {
            "name": "userMinOut",
            "type": "uint256"
          },
          {
            "name": "effectiveMinOut",
            "type": "uint256"
          },
          {
            "name": "estGas",
            "type": "uint256"
          },
          {
            "name": "hops",
            "type": "uint256"
          },
          {
            "name": "legs",
            "type": "uint256"
          },
          {
            "name": "topology",
            "type": "uint8"
          },
          {
            "name": "bridgeUsed",
            "type": "address"
          },
          {
            "name": "canExecute",
            "type": "bool"
          }
        ],
        "name": "pv",
        "type": "tuple"
      },
      {
        "components": [
          {
            "components": [
              {
                "name": "tokenIn",
                "type": "address"
              },
              {
                "name": "tokenOut",
                "type": "address"
              },
              {
                "name": "amountIn",
                "type": "uint256"
              },
              {
                "name": "expectedOut",
                "type": "uint256"
              },
              {
                "components": [
                  {
                    "name": "pool",
                    "type": "address"
                  },
                  {
                    "name": "hooks",
                    "type": "address"
                  },
                  {
                    "name": "kind",
                    "type": "uint8"
                  },
                  {
                    "name": "fee",
                    "type": "uint24"
                  },
                  {
                    "name": "tickSpacing",
                    "type": "int24"
                  },
                  {
                    "name": "zeroForOne",
                    "type": "bool"
                  },
                  {
                    "name": "stable",
                    "type": "bool"
                  },
                  {
                    "name": "amountIn",
                    "type": "uint256"
                  },
                  {
                    "name": "expectedOut",
                    "type": "uint256"
                  },
                  {
                    "name": "auxId",
                    "type": "bytes32"
                  }
                ],
                "name": "legs",
                "type": "tuple[]"
              }
            ],
            "name": "hops",
            "type": "tuple[]"
          },
          {
            "name": "totalOut",
            "type": "uint256"
          },
          {
            "name": "singleOut",
            "type": "uint256"
          },
          {
            "name": "singleOutFloor",
            "type": "uint256"
          },
          {
            "name": "expectedImpactBps",
            "type": "uint256"
          },
          {
            "name": "confidenceWad",
            "type": "uint256"
          },
          {
            "name": "estGas",
            "type": "uint256"
          },
          {
            "name": "hasSurplus",
            "type": "bool"
          },
          {
            "name": "isV4Bundle",
            "type": "bool"
          }
        ],
        "name": "fallbackRoute",
        "type": "tuple"
      },
      {
        "name": "hasFallback",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "tIn",
        "type": "address"
      },
      {
        "name": "tOut",
        "type": "address"
      },
      {
        "name": "amountIn",
        "type": "uint256"
      }
    ],
    "name": "previewPlanExact",
    "outputs": [
      {
        "components": [
          {
            "components": [
              {
                "name": "tokenIn",
                "type": "address"
              },
              {
                "name": "tokenOut",
                "type": "address"
              },
              {
                "name": "amountIn",
                "type": "uint256"
              },
              {
                "name": "expectedOut",
                "type": "uint256"
              },
              {
                "components": [
                  {
                    "name": "pool",
                    "type": "address"
                  },
                  {
                    "name": "hooks",
                    "type": "address"
                  },
                  {
                    "name": "kind",
                    "type": "uint8"
                  },
                  {
                    "name": "fee",
                    "type": "uint24"
                  },
                  {
                    "name": "tickSpacing",
                    "type": "int24"
                  },
                  {
                    "name": "zeroForOne",
                    "type": "bool"
                  },
                  {
                    "name": "stable",
                    "type": "bool"
                  },
                  {
                    "name": "amountIn",
                    "type": "uint256"
                  },
                  {
                    "name": "expectedOut",
                    "type": "uint256"
                  },
                  {
                    "name": "auxId",
                    "type": "bytes32"
                  }
                ],
                "name": "legs",
                "type": "tuple[]"
              }
            ],
            "name": "hops",
            "type": "tuple[]"
          },
          {
            "name": "totalOut",
            "type": "uint256"
          },
          {
            "name": "singleOut",
            "type": "uint256"
          },
          {
            "name": "singleOutFloor",
            "type": "uint256"
          },
          {
            "name": "expectedImpactBps",
            "type": "uint256"
          },
          {
            "name": "confidenceWad",
            "type": "uint256"
          },
          {
            "name": "estGas",
            "type": "uint256"
          },
          {
            "name": "hasSurplus",
            "type": "bool"
          },
          {
            "name": "isV4Bundle",
            "type": "bool"
          }
        ],
        "name": "route",
        "type": "tuple"
      },
      {
        "name": "exactOut",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "tIn",
        "type": "address"
      },
      {
        "name": "tOut",
        "type": "address"
      },
      {
        "name": "amountIn",
        "type": "uint256"
      },
      {
        "name": "userMinOut",
        "type": "uint256"
      }
    ],
    "name": "previewPlanWithMinOut",
    "outputs": [
      {
        "components": [
          {
            "components": [
              {
                "components": [
                  {
                    "name": "tokenIn",
                    "type": "address"
                  },
                  {
                    "name": "tokenOut",
                    "type": "address"
                  },
                  {
                    "name": "amountIn",
                    "type": "uint256"
                  },
                  {
                    "name": "expectedOut",
                    "type": "uint256"
                  },
                  {
                    "components": [
                      {
                        "name": "pool",
                        "type": "address"
                      },
                      {
                        "name": "hooks",
                        "type": "address"
                      },
                      {
                        "name": "kind",
                        "type": "uint8"
                      },
                      {
                        "name": "fee",
                        "type": "uint24"
                      },
                      {
                        "name": "tickSpacing",
                        "type": "int24"
                      },
                      {
                        "name": "zeroForOne",
                        "type": "bool"
                      },
                      {
                        "name": "stable",
                        "type": "bool"
                      },
                      {
                        "name": "amountIn",
                        "type": "uint256"
                      },
                      {
                        "name": "expectedOut",
                        "type": "uint256"
                      },
                      {
                        "name": "auxId",
                        "type": "bytes32"
                      }
                    ],
                    "name": "legs",
                    "type": "tuple[]"
                  }
                ],
                "name": "hops",
                "type": "tuple[]"
              },
              {
                "name": "totalOut",
                "type": "uint256"
              },
              {
                "name": "singleOut",
                "type": "uint256"
              },
              {
                "name": "singleOutFloor",
                "type": "uint256"
              },
              {
                "name": "expectedImpactBps",
                "type": "uint256"
              },
              {
                "name": "confidenceWad",
                "type": "uint256"
              },
              {
                "name": "estGas",
                "type": "uint256"
              },
              {
                "name": "hasSurplus",
                "type": "bool"
              },
              {
                "name": "isV4Bundle",
                "type": "bool"
              }
            ],
            "name": "route",
            "type": "tuple"
          },
          {
            "name": "grossOut",
            "type": "uint256"
          },
          {
            "name": "protocolFee",
            "type": "uint256"
          },
          {
            "name": "safetyBuffer",
            "type": "uint256"
          },
          {
            "name": "netOut",
            "type": "uint256"
          },
          {
            "name": "ironFloor",
            "type": "uint256"
          },
          {
            "name": "userMinOut",
            "type": "uint256"
          },
          {
            "name": "effectiveMinOut",
            "type": "uint256"
          },
          {
            "name": "estGas",
            "type": "uint256"
          },
          {
            "name": "hops",
            "type": "uint256"
          },
          {
            "name": "legs",
            "type": "uint256"
          },
          {
            "name": "topology",
            "type": "uint8"
          },
          {
            "name": "bridgeUsed",
            "type": "address"
          },
          {
            "name": "canExecute",
            "type": "bool"
          }
        ],
        "name": "pv",
        "type": "tuple"
      },
      {
        "components": [
          {
            "components": [
              {
                "name": "tokenIn",
                "type": "address"
              },
              {
                "name": "tokenOut",
                "type": "address"
              },
              {
                "name": "amountIn",
                "type": "uint256"
              },
              {
                "name": "expectedOut",
                "type": "uint256"
              },
              {
                "components": [
                  {
                    "name": "pool",
                    "type": "address"
                  },
                  {
                    "name": "hooks",
                    "type": "address"
                  },
                  {
                    "name": "kind",
                    "type": "uint8"
                  },
                  {
                    "name": "fee",
                    "type": "uint24"
                  },
                  {
                    "name": "tickSpacing",
                    "type": "int24"
                  },
                  {
                    "name": "zeroForOne",
                    "type": "bool"
                  },
                  {
                    "name": "stable",
                    "type": "bool"
                  },
                  {
                    "name": "amountIn",
                    "type": "uint256"
                  },
                  {
                    "name": "expectedOut",
                    "type": "uint256"
                  },
                  {
                    "name": "auxId",
                    "type": "bytes32"
                  }
                ],
                "name": "legs",
                "type": "tuple[]"
              }
            ],
            "name": "hops",
            "type": "tuple[]"
          },
          {
            "name": "totalOut",
            "type": "uint256"
          },
          {
            "name": "singleOut",
            "type": "uint256"
          },
          {
            "name": "singleOutFloor",
            "type": "uint256"
          },
          {
            "name": "expectedImpactBps",
            "type": "uint256"
          },
          {
            "name": "confidenceWad",
            "type": "uint256"
          },
          {
            "name": "estGas",
            "type": "uint256"
          },
          {
            "name": "hasSurplus",
            "type": "bool"
          },
          {
            "name": "isV4Bundle",
            "type": "bool"
          }
        ],
        "name": "fallbackRoute",
        "type": "tuple"
      },
      {
        "name": "hasFallback",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "components": [
              {
                "name": "tokenIn",
                "type": "address"
              },
              {
                "name": "tokenOut",
                "type": "address"
              },
              {
                "name": "amountIn",
                "type": "uint256"
              },
              {
                "name": "expectedOut",
                "type": "uint256"
              },
              {
                "components": [
                  {
                    "name": "pool",
                    "type": "address"
                  },
                  {
                    "name": "hooks",
                    "type": "address"
                  },
                  {
                    "name": "kind",
                    "type": "uint8"
                  },
                  {
                    "name": "fee",
                    "type": "uint24"
                  },
                  {
                    "name": "tickSpacing",
                    "type": "int24"
                  },
                  {
                    "name": "zeroForOne",
                    "type": "bool"
                  },
                  {
                    "name": "stable",
                    "type": "bool"
                  },
                  {
                    "name": "amountIn",
                    "type": "uint256"
                  },
                  {
                    "name": "expectedOut",
                    "type": "uint256"
                  },
                  {
                    "name": "auxId",
                    "type": "bytes32"
                  }
                ],
                "name": "legs",
                "type": "tuple[]"
              }
            ],
            "name": "hops",
            "type": "tuple[]"
          },
          {
            "name": "totalOut",
            "type": "uint256"
          },
          {
            "name": "singleOut",
            "type": "uint256"
          },
          {
            "name": "singleOutFloor",
            "type": "uint256"
          },
          {
            "name": "expectedImpactBps",
            "type": "uint256"
          },
          {
            "name": "confidenceWad",
            "type": "uint256"
          },
          {
            "name": "estGas",
            "type": "uint256"
          },
          {
            "name": "hasSurplus",
            "type": "bool"
          },
          {
            "name": "isV4Bundle",
            "type": "bool"
          }
        ],
        "name": "route",
        "type": "tuple"
      },
      {
        "name": "userMinOut",
        "type": "uint256"
      }
    ],
    "name": "previewRoute",
    "outputs": [
      {
        "components": [
          {
            "components": [
              {
                "components": [
                  {
                    "name": "tokenIn",
                    "type": "address"
                  },
                  {
                    "name": "tokenOut",
                    "type": "address"
                  },
                  {
                    "name": "amountIn",
                    "type": "uint256"
                  },
                  {
                    "name": "expectedOut",
                    "type": "uint256"
                  },
                  {
                    "components": [
                      {
                        "name": "pool",
                        "type": "address"
                      },
                      {
                        "name": "hooks",
                        "type": "address"
                      },
                      {
                        "name": "kind",
                        "type": "uint8"
                      },
                      {
                        "name": "fee",
                        "type": "uint24"
                      },
                      {
                        "name": "tickSpacing",
                        "type": "int24"
                      },
                      {
                        "name": "zeroForOne",
                        "type": "bool"
                      },
                      {
                        "name": "stable",
                        "type": "bool"
                      },
                      {
                        "name": "amountIn",
                        "type": "uint256"
                      },
                      {
                        "name": "expectedOut",
                        "type": "uint256"
                      },
                      {
                        "name": "auxId",
                        "type": "bytes32"
                      }
                    ],
                    "name": "legs",
                    "type": "tuple[]"
                  }
                ],
                "name": "hops",
                "type": "tuple[]"
              },
              {
                "name": "totalOut",
                "type": "uint256"
              },
              {
                "name": "singleOut",
                "type": "uint256"
              },
              {
                "name": "singleOutFloor",
                "type": "uint256"
              },
              {
                "name": "expectedImpactBps",
                "type": "uint256"
              },
              {
                "name": "confidenceWad",
                "type": "uint256"
              },
              {
                "name": "estGas",
                "type": "uint256"
              },
              {
                "name": "hasSurplus",
                "type": "bool"
              },
              {
                "name": "isV4Bundle",
                "type": "bool"
              }
            ],
            "name": "route",
            "type": "tuple"
          },
          {
            "name": "grossOut",
            "type": "uint256"
          },
          {
            "name": "protocolFee",
            "type": "uint256"
          },
          {
            "name": "safetyBuffer",
            "type": "uint256"
          },
          {
            "name": "netOut",
            "type": "uint256"
          },
          {
            "name": "ironFloor",
            "type": "uint256"
          },
          {
            "name": "userMinOut",
            "type": "uint256"
          },
          {
            "name": "effectiveMinOut",
            "type": "uint256"
          },
          {
            "name": "estGas",
            "type": "uint256"
          },
          {
            "name": "hops",
            "type": "uint256"
          },
          {
            "name": "legs",
            "type": "uint256"
          },
          {
            "name": "topology",
            "type": "uint8"
          },
          {
            "name": "bridgeUsed",
            "type": "address"
          },
          {
            "name": "canExecute",
            "type": "bool"
          }
        ],
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "solver",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "data",
        "type": "bytes"
      }
    ],
    "name": "unlockCallback",
    "outputs": [
      {
        "name": "",
        "type": "bytes"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "code",
        "type": "uint16"
      }
    ],
    "name": "SolverE",
    "type": "error"
  },
  {
    "inputs": [
      {
        "name": "code",
        "type": "uint16"
      }
    ],
    "name": "HubE",
    "type": "error"
  },
  {
    "inputs": [
      {
        "name": "code",
        "type": "uint16"
      }
    ],
    "name": "RouterE",
    "type": "error"
  }
] as const;

export const ROUTER_ABI = [
  {
    "inputs": [
      {
        "name": "code",
        "type": "uint16"
      }
    ],
    "name": "RouterE",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "name": "id",
        "type": "uint8"
      },
      {
        "indexed": false,
        "name": "who",
        "type": "address"
      }
    ],
    "name": "Cfg",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "user",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "tokenOut",
        "type": "address"
      },
      {
        "indexed": false,
        "name": "quoted",
        "type": "uint256"
      },
      {
        "indexed": false,
        "name": "realized",
        "type": "uint256"
      },
      {
        "indexed": false,
        "name": "floorUsed",
        "type": "uint256"
      },
      {
        "indexed": false,
        "name": "blockNumber",
        "type": "uint256"
      }
    ],
    "name": "ExecutionProof",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "token",
        "type": "address"
      },
      {
        "indexed": false,
        "name": "amount",
        "type": "uint256"
      },
      {
        "indexed": false,
        "name": "toT1",
        "type": "uint256"
      },
      {
        "indexed": false,
        "name": "toT2",
        "type": "uint256"
      }
    ],
    "name": "Fee",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "name": "paused",
        "type": "bool"
      }
    ],
    "name": "PausedSet",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "token",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "to",
        "type": "address"
      },
      {
        "indexed": false,
        "name": "eta",
        "type": "uint256"
      }
    ],
    "name": "RescueQueued",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "token",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "to",
        "type": "address"
      },
      {
        "indexed": false,
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "Rescued",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "user",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "tokenIn",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "tokenOut",
        "type": "address"
      },
      {
        "indexed": false,
        "name": "amountIn",
        "type": "uint256"
      },
      {
        "indexed": false,
        "name": "amountOut",
        "type": "uint256"
      },
      {
        "indexed": false,
        "name": "legs",
        "type": "uint256"
      }
    ],
    "name": "Swap",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "VERSION",
    "outputs": [
      {
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "admin",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "token",
        "type": "address"
      },
      {
        "name": "to",
        "type": "address"
      }
    ],
    "name": "cancelRescue",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "controlRenounced",
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "token",
        "type": "address"
      },
      {
        "name": "to",
        "type": "address"
      }
    ],
    "name": "executeRescue",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "hub",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "paused",
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "permit2",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "token",
        "type": "address"
      },
      {
        "name": "to",
        "type": "address"
      }
    ],
    "name": "queueRescue",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "renounceControl",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ],
    "name": "rescueEta",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "components": [
              {
                "name": "tokenIn",
                "type": "address"
              },
              {
                "name": "tokenOut",
                "type": "address"
              },
              {
                "name": "amountIn",
                "type": "uint256"
              },
              {
                "name": "expectedOut",
                "type": "uint256"
              },
              {
                "components": [
                  {
                    "name": "pool",
                    "type": "address"
                  },
                  {
                    "name": "hooks",
                    "type": "address"
                  },
                  {
                    "name": "kind",
                    "type": "uint8"
                  },
                  {
                    "name": "fee",
                    "type": "uint24"
                  },
                  {
                    "name": "tickSpacing",
                    "type": "int24"
                  },
                  {
                    "name": "zeroForOne",
                    "type": "bool"
                  },
                  {
                    "name": "stable",
                    "type": "bool"
                  },
                  {
                    "name": "amountIn",
                    "type": "uint256"
                  },
                  {
                    "name": "expectedOut",
                    "type": "uint256"
                  },
                  {
                    "name": "auxId",
                    "type": "bytes32"
                  }
                ],
                "name": "legs",
                "type": "tuple[]"
              }
            ],
            "name": "hops",
            "type": "tuple[]"
          },
          {
            "name": "totalOut",
            "type": "uint256"
          },
          {
            "name": "singleOut",
            "type": "uint256"
          },
          {
            "name": "singleOutFloor",
            "type": "uint256"
          },
          {
            "name": "expectedImpactBps",
            "type": "uint256"
          },
          {
            "name": "confidenceWad",
            "type": "uint256"
          },
          {
            "name": "estGas",
            "type": "uint256"
          },
          {
            "name": "hasSurplus",
            "type": "bool"
          },
          {
            "name": "isV4Bundle",
            "type": "bool"
          }
        ],
        "name": "route",
        "type": "tuple"
      },
      {
        "name": "amountIn",
        "type": "uint256"
      },
      {
        "name": "userMinOut",
        "type": "uint256"
      },
      {
        "name": "recipient",
        "type": "address"
      },
      {
        "name": "deadline",
        "type": "uint256"
      },
      {
        "name": "payer",
        "type": "address"
      }
    ],
    "name": "selfExecutePrePulled",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "a",
        "type": "address"
      }
    ],
    "name": "setAdmin",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "b",
        "type": "bool"
      }
    ],
    "name": "setPaused",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "p",
        "type": "address"
      }
    ],
    "name": "setPermit2",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "t1",
        "type": "address"
      },
      {
        "name": "t2",
        "type": "address"
      }
    ],
    "name": "setTreasuries",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "w",
        "type": "address"
      }
    ],
    "name": "setWeth",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "solver",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "tokenIn",
        "type": "address"
      },
      {
        "name": "tokenOut",
        "type": "address"
      },
      {
        "name": "amountIn",
        "type": "uint256"
      },
      {
        "name": "userMinOut",
        "type": "uint256"
      },
      {
        "name": "recipient",
        "type": "address"
      },
      {
        "name": "deadline",
        "type": "uint256"
      }
    ],
    "name": "swapBestExactIn",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "components": [
              {
                "name": "tokenIn",
                "type": "address"
              },
              {
                "name": "tokenOut",
                "type": "address"
              },
              {
                "name": "amountIn",
                "type": "uint256"
              },
              {
                "name": "expectedOut",
                "type": "uint256"
              },
              {
                "components": [
                  {
                    "name": "pool",
                    "type": "address"
                  },
                  {
                    "name": "hooks",
                    "type": "address"
                  },
                  {
                    "name": "kind",
                    "type": "uint8"
                  },
                  {
                    "name": "fee",
                    "type": "uint24"
                  },
                  {
                    "name": "tickSpacing",
                    "type": "int24"
                  },
                  {
                    "name": "zeroForOne",
                    "type": "bool"
                  },
                  {
                    "name": "stable",
                    "type": "bool"
                  },
                  {
                    "name": "amountIn",
                    "type": "uint256"
                  },
                  {
                    "name": "expectedOut",
                    "type": "uint256"
                  },
                  {
                    "name": "auxId",
                    "type": "bytes32"
                  }
                ],
                "name": "legs",
                "type": "tuple[]"
              }
            ],
            "name": "hops",
            "type": "tuple[]"
          },
          {
            "name": "totalOut",
            "type": "uint256"
          },
          {
            "name": "singleOut",
            "type": "uint256"
          },
          {
            "name": "singleOutFloor",
            "type": "uint256"
          },
          {
            "name": "expectedImpactBps",
            "type": "uint256"
          },
          {
            "name": "confidenceWad",
            "type": "uint256"
          },
          {
            "name": "estGas",
            "type": "uint256"
          },
          {
            "name": "hasSurplus",
            "type": "bool"
          },
          {
            "name": "isV4Bundle",
            "type": "bool"
          }
        ],
        "name": "route",
        "type": "tuple"
      },
      {
        "name": "amountIn",
        "type": "uint256"
      },
      {
        "name": "userMinOut",
        "type": "uint256"
      },
      {
        "name": "recipient",
        "type": "address"
      },
      {
        "name": "deadline",
        "type": "uint256"
      }
    ],
    "name": "swapExactIn",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "components": [
              {
                "name": "tokenIn",
                "type": "address"
              },
              {
                "name": "tokenOut",
                "type": "address"
              },
              {
                "name": "amountIn",
                "type": "uint256"
              },
              {
                "name": "expectedOut",
                "type": "uint256"
              },
              {
                "components": [
                  {
                    "name": "pool",
                    "type": "address"
                  },
                  {
                    "name": "hooks",
                    "type": "address"
                  },
                  {
                    "name": "kind",
                    "type": "uint8"
                  },
                  {
                    "name": "fee",
                    "type": "uint24"
                  },
                  {
                    "name": "tickSpacing",
                    "type": "int24"
                  },
                  {
                    "name": "zeroForOne",
                    "type": "bool"
                  },
                  {
                    "name": "stable",
                    "type": "bool"
                  },
                  {
                    "name": "amountIn",
                    "type": "uint256"
                  },
                  {
                    "name": "expectedOut",
                    "type": "uint256"
                  },
                  {
                    "name": "auxId",
                    "type": "bytes32"
                  }
                ],
                "name": "legs",
                "type": "tuple[]"
              }
            ],
            "name": "hops",
            "type": "tuple[]"
          },
          {
            "name": "totalOut",
            "type": "uint256"
          },
          {
            "name": "singleOut",
            "type": "uint256"
          },
          {
            "name": "singleOutFloor",
            "type": "uint256"
          },
          {
            "name": "expectedImpactBps",
            "type": "uint256"
          },
          {
            "name": "confidenceWad",
            "type": "uint256"
          },
          {
            "name": "estGas",
            "type": "uint256"
          },
          {
            "name": "hasSurplus",
            "type": "bool"
          },
          {
            "name": "isV4Bundle",
            "type": "bool"
          }
        ],
        "name": "route",
        "type": "tuple"
      },
      {
        "name": "userMinOut",
        "type": "uint256"
      },
      {
        "name": "recipient",
        "type": "address"
      },
      {
        "name": "deadline",
        "type": "uint256"
      }
    ],
    "name": "swapExactInNative",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "components": [
              {
                "name": "tokenIn",
                "type": "address"
              },
              {
                "name": "tokenOut",
                "type": "address"
              },
              {
                "name": "amountIn",
                "type": "uint256"
              },
              {
                "name": "expectedOut",
                "type": "uint256"
              },
              {
                "components": [
                  {
                    "name": "pool",
                    "type": "address"
                  },
                  {
                    "name": "hooks",
                    "type": "address"
                  },
                  {
                    "name": "kind",
                    "type": "uint8"
                  },
                  {
                    "name": "fee",
                    "type": "uint24"
                  },
                  {
                    "name": "tickSpacing",
                    "type": "int24"
                  },
                  {
                    "name": "zeroForOne",
                    "type": "bool"
                  },
                  {
                    "name": "stable",
                    "type": "bool"
                  },
                  {
                    "name": "amountIn",
                    "type": "uint256"
                  },
                  {
                    "name": "expectedOut",
                    "type": "uint256"
                  },
                  {
                    "name": "auxId",
                    "type": "bytes32"
                  }
                ],
                "name": "legs",
                "type": "tuple[]"
              }
            ],
            "name": "hops",
            "type": "tuple[]"
          },
          {
            "name": "totalOut",
            "type": "uint256"
          },
          {
            "name": "singleOut",
            "type": "uint256"
          },
          {
            "name": "singleOutFloor",
            "type": "uint256"
          },
          {
            "name": "expectedImpactBps",
            "type": "uint256"
          },
          {
            "name": "confidenceWad",
            "type": "uint256"
          },
          {
            "name": "estGas",
            "type": "uint256"
          },
          {
            "name": "hasSurplus",
            "type": "bool"
          },
          {
            "name": "isV4Bundle",
            "type": "bool"
          }
        ],
        "name": "route",
        "type": "tuple"
      },
      {
        "name": "amountIn",
        "type": "uint256"
      },
      {
        "name": "userMinOut",
        "type": "uint256"
      },
      {
        "name": "recipient",
        "type": "address"
      },
      {
        "name": "deadline",
        "type": "uint256"
      },
      {
        "components": [
          {
            "components": [
              {
                "name": "token",
                "type": "address"
              },
              {
                "name": "amount",
                "type": "uint256"
              }
            ],
            "name": "permitted",
            "type": "tuple"
          },
          {
            "name": "nonce",
            "type": "uint256"
          },
          {
            "name": "deadline",
            "type": "uint256"
          }
        ],
        "name": "permit",
        "type": "tuple"
      },
      {
        "name": "signature",
        "type": "bytes"
      }
    ],
    "name": "swapExactInWithPermit2",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "treasury1",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "treasury2",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "data",
        "type": "bytes"
      }
    ],
    "name": "unlockCallback",
    "outputs": [
      {
        "name": "",
        "type": "bytes"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "weth",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "code",
        "type": "uint16"
      }
    ],
    "name": "QuoterE",
    "type": "error"
  },
  {
    "inputs": [
      {
        "name": "code",
        "type": "uint16"
      }
    ],
    "name": "SolverE",
    "type": "error"
  },
  {
    "inputs": [
      {
        "name": "code",
        "type": "uint16"
      }
    ],
    "name": "HubE",
    "type": "error"
  }
] as const;

export const BLAZE_ERRORS_ABI = [
  {
    "inputs": [
      {
        "name": "code",
        "type": "uint16"
      }
    ],
    "name": "QuoterE",
    "type": "error"
  },
  {
    "inputs": [
      {
        "name": "code",
        "type": "uint16"
      }
    ],
    "name": "SolverE",
    "type": "error"
  },
  {
    "inputs": [
      {
        "name": "code",
        "type": "uint16"
      }
    ],
    "name": "HubE",
    "type": "error"
  },
  {
    "inputs": [
      {
        "name": "code",
        "type": "uint16"
      }
    ],
    "name": "RouterE",
    "type": "error"
  }
] as const;

export const ABI_SOURCE_REVISION = "07c85636f4116f98ddcfffb66e4477d7da7e9928" as const;
